backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
media_library:
  name: cloudinary
  config:
    cloud_name: dzgf40ghh
    api_key: 958272413457741
i18n:
  structure: multiple_folders
  locales: [en, es]
  default_locale: en
collections:
  - name: layout
    label: Layout
    i18n:
      structure: single_file
      locales: [en, es]
    files:
      - name: base
        label: Base
        i18n: true
        file: content/layout/base.md
        fields:
          - { name: 'mainImage', label: 'Logo image', widget: 'image' }
          - { name: 'title', label: 'Title', widget: string, i18n: true }
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Home'
        name: home
        file: 'content/en/home.md'
        fields:
          - label: 'Hero title'
            name: heroTitle
            widget: string
