backend:
  # name: test-repo
  name: git-gateway
  repo: RBoraurito/its-amy-blog
  branch: main
  # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
media_library:
  name: cloudinary
  config:
    cloud_name: dzgf40ghh
    api_key: 958272413457741
i18n:
  structure: multiple_folders
  locales: [en, es]
  default_locale: en
collections:
  - name: layout
    label: Layout
    i18n:
      structure: single_file
      locales: [en, es]
    files:
      - name: base
        label: Base
        i18n: true
        file: content/layout/base.md
        fields:
          - { name: 'mainImage', label: 'Logo image', widget: 'image' }
          - { name: 'title', label: 'Title', widget: string, i18n: true }
          - name: 'cta'
            label: 'Call to action'
            widget: 'object'
            i18n: true
            fields:
              - { name: 'text', label: 'Text', widget: 'string', i18n: true }
              - name: 'link'
                label: 'Link (url)'
                widget: 'string'
                i18n: true
              - name: 'isExternal'
                label: 'Is external link?'
                required: false
                default: false
                widget: 'boolean'
                i18n: true
          - name: 'links'
            label: 'Navigation links'
            widget: 'list'
            i18n: true
            fields:
              - { name: 'text', label: 'Text', widget: 'string', i18n: true }
              - name: 'link'
                label: 'Link (url)'
                widget: 'string'
                i18n: true
              - name: 'isExternal'
                label: 'Is external link?'
                widget: boolean
                i18n: true
                required: false
                default: false
              - name: 'isOnFooter'
                label: 'Is on footer?'
                widget: boolean
                required: false
                default: false
                i18n: true
  - name: 'pages'
    label: 'Pages'
    i18n:
      structure: single_file
      locales: [en, es]
    files:
      - label: 'Home'
        name: home
        file: 'content/en/home.md'
        fields:
          - label: 'Hero title'
            name: heroTitle
            widget: string
      - label: 'About'
        name: aboutMe
        file: 'content/pages/about-me.md'
        i18n: true
        fields:
          - label: 'Meta: Title'
            name: metaTitle
            i18n: true
            widget: string
          - label: 'Meta: description'
            name: metaDescription
            i18n: true
            widget: text
          - label: 'Meta: Image'
            name: metaImage
            i18n: true
            widget: image
          - label: 'About title'
            name: title
            i18n: true
            widget: string
          - label: "About first section paragraph"
            name: firstParagraph
            i18n: true
            widget: markdown
          - label: "About first section Image"
            name: firstImage
            widget: image
          - label: "Skills title"
            name: skillsTitle
            i18n: true
            widget: string
          - label: "Skills subtitle"
            name: skillsSubtitle
            i18n: true
            widget: string
          - label: "My skills"
            name: skills
            widget: list
            i18n: true
            fields:
              - label: "Title"
                name: title
                i18n: true
                widget: string
              - label: "Description"
                name: description
                i18n: true
                widget: text
          - label: "Education title"
            name: educationTitle
            i18n: true
            widget: string
          - label: "Education subtitle"
            name: educationSubTitle
            i18n: true
            widget: string
          - label: "Education items"
            name: education
            i18n: true
            widget: list
            fields:
              - label: "Title"
                name: title
                i18n: true
                widget: string
              - label: "Description"
                name: description
                i18n: true
                widget: text
              - label: "Course url"
                name: url
                i18n: true
                widget: string
              - label: "Course image"
                name: image
                i18n: true
                widget: image
  - label: 'Blog'
    name: blog
    folder: 'content/pages/blog'
    create: true
    i18n:
      structure: single_file
      locales: [en, es]
    identifier_field: title
    slug: "{{title}}-{{day}}"
    fields:
      - label: 'Meta: Title'
        name: metaTitle
        i18n: true
        widget: string
      - label: 'Meta: description'
        name: metaDescription
        i18n: true
        widget: text
      - label: 'Meta: Image'
        name: metaImage
        i18n: true
        widget: image
      - label: "Publish Date"
        name: publishDate
        i18n: true
        widget: date
      - label: "Title"
        name: title
        i18n: true
        widget: string
      - label: "Description"
        name: description
        i18n: true
        widget: text
      - label:  "Featured Image"
        name: featuredImage
        i18n: true
        widget: image
      - label: "Tag"
        name: tag
        i18n: true
        widget: select
        options: ["Virtual Assistance", "Asistencia Virtual", "Productivity", "Productividad", "Social Media", "Redes Sociales", "Project Management", "Manejo de proyectos"]
      - label: "Content"
        name: content
        i18n: true
        widget: markdown
